name: Jdate
description: 'Download/install the latest version of jdate'
author: Davoud Arsalani <ielts@davoudarsalani.ir>

inputs:
  source:
    required: false
    default: 'docker-jdate'

runs:
  using: 'composite'
  steps:
    - name: Setting up python
      if: ${{ inputs.source == 'jdatetime' }}
      uses: actions/setup-python@v2

    - name: Pulling/cloning/downloading
      shell: bash
      run: |
        case '${{ inputs.source }}' in
          docker-khayyam )
            docker pull davoudarsalani/khayyam
          ;;
          docker-persiantools )
            docker pull davoudarsalani/persiantools
          ;;
          docker-jdatetime )
            docker pull davoudarsalani/jdatetime
          ;;
          docker-jdate )
            docker pull davoudarsalani/jdate
          ;;
          * )
            ## set timezone
            sudo ln -fs /usr/share/zoneinfo/Asia/Tehran /etc/localtime
            sudo hwclock --systohc --utc
            sudo timedatectl set-ntp true

            wget -q 'https://raw.githubusercontent.com/davoudarsalani/scripts/master/install-jdate.sh'
            chmod +x ./install-jdate
            ./install-date '${{ inputs.source }}'
          ;;
        esac

branding:
  icon: calendar
  color: blue
